import type { CSSProperties } from "react";

export const plotsListStyles: { [key: string]: CSSProperties } = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#F8FAFC",
  },
  main: {
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "32px 40px",
    paddingBottom: "120px",
  },
  headerTitle: {
    fontSize: "24px",
    fontWeight: 700,
    color: "#1F2937",
    margin: "0 0 24px 0",
  },
  plotsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  empty: {
    textAlign: "center" as const,
    padding: "60px 20px",
    color: "#6B7280",
  },
  emptyTitle: {
    fontSize: "18px",
    margin: "0 0 8px 0",
  },
  emptyText: {
    fontSize: "14px",
    margin: 0,
  },
  loadingText: {
    textAlign: "center" as const,
    color: "#6B7280",
    fontSize: "16px",
    padding: "40px 0",
  },
  fab: {
    position: "fixed" as const,
    bottom: "32px",
    right: "calc(50% - 700px + 40px)",
    width: "56px",
    height: "56px",
    backgroundColor: "#22C55E",
    color: "white",
    borderRadius: "50%",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    zIndex: 100,
  },
  modalOverlay: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: "20px",
  },
  modal: {
    backgroundColor: "white",
    borderRadius: "16px",
    padding: "24px 28px",
    width: "100%",
    maxWidth: "400px",
    boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.2)",
    maxHeight: "90vh",
    overflowY: "auto" as const,
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "16px",
  },
  modalTitle: {
    fontSize: "18px",
    fontWeight: 600,
    color: "#1F2937",
    margin: 0,
  },
  modalBody: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "16px",
  },
  fieldGroup: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    width: "100%",
  },
  label: {
    fontSize: "14px",
    fontWeight: 500,
    color: "#374151",
    marginBottom: "2px",
  },
  sizeRow: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
    width: "100%",
  },
  sizeSeparator: {
    color: "#6B7280",
    fontSize: "16px",
    fontWeight: 600,
    flexShrink: 0,
  },
  modalActions: {
    display: "flex",
    gap: "12px",
    marginTop: "4px",
  },
};
