// src/PageStyles/Tasks.styles.ts
import type { CSSProperties } from 'react';

export const tasksStyles: { [key: string]: CSSProperties } = {
  page: {
    minHeight: '100vh',
    backgroundColor: '#F8FAFC',
  },
  main: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '32px 40px',
    paddingBottom: '100px',
  },
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
  },
  pageTitle: {
    fontSize: '28px',
    fontWeight: 'bold',
    color: '#1F2937',
    margin: '0 0 8px 0',
  },
  pageSubtitle: {
    fontSize: '14px',
    color: '#6B7280',
    margin: 0,
  },
  addButton: {
    padding: '10px 20px',
    backgroundColor: '#22C55E',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  filterContainer: {
    backgroundColor: 'white',
    borderRadius: '8px',
    padding: '16px 20px',
    marginBottom: '24px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  },
  filterButton: {
    padding: '8px 16px',
    borderRadius: '16px',
    border: '1px solid',
    fontSize: '13px',
    fontWeight: 500,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  filterBadge: {
    borderRadius: '10px',
    padding: '2px 8px',
    fontSize: '11px',
    minWidth: '20px',
    textAlign: 'center',
  },
  emptyState: {
    textAlign: 'center',
    padding: '60px 20px',
    color: '#6B7280',
    backgroundColor: 'white',
    borderRadius: '8px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  emptyTitle: {
    fontSize: '18px',
    margin: '0 0 8px 0',
  },
  emptyText: {
    fontSize: '14px',
    margin: 0,
  },
  taskList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  plotGroupTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#1F2937',
    margin: '0 0 12px 0',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  plotGroupCount: {
    fontSize: '13px',
    color: '#6B7280',
    fontWeight: 400,
  },
  tasksContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  taskCard: {
    backgroundColor: 'white',
    borderRadius: '8px',
    padding: '16px 20px',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    accentColor: '#22C55E',
    cursor: 'pointer',
    flexShrink: 0,
  },
  taskContent: {
    flex: 1,
    minWidth: 0,
  },
  taskText: {
    fontSize: '15px',
    fontWeight: 500,
    marginBottom: '4px',
  },
  taskMeta: {
    fontSize: '12px',
    color: '#6B7280',
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
  },
  taskDate: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  overdueBadge: {
    color: '#DC2626',
    fontWeight: 500,
    marginLeft: '4px',
  },
  priorityBadge: {
    padding: '2px 8px',
    borderRadius: '10px',
    fontSize: '11px',
    fontWeight: 500,
  },
  taskActions: {
    display: 'flex',
    gap: '8px',
    flexShrink: 0,
  },
  editButton: {
    width: '36px',
    height: '36px',
    borderRadius: '6px',
    backgroundColor: '#DCFCE7',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteButton: {
    width: '36px',
    height: '36px',
    borderRadius: '6px',
    backgroundColor: '#FEE2E2',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fab: {
    position: 'fixed',
    bottom: '32px',
    right: 'calc(50% - 700px + 40px)',
    width: '56px',
    height: '56px',
    backgroundColor: '#22C55E',
    color: 'white',
    borderRadius: '50%',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
    zIndex: 100,
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '24px',
    width: '100%',
    maxWidth: '440px',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '20px',
  },
  modalTitle: {
    fontSize: '20px',
    fontWeight: 600,
    color: '#1F2937',
    margin: 0,
  },
  modalCloseButton: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    backgroundColor: '#FEE2E2',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  modalLabel: {
    display: 'block',
    fontSize: '14px',
    color: '#6B7280',
    marginBottom: '6px',
  },
  modalInput: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #E5E7EB',
    borderRadius: '6px',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box',
  },
  modalSelect: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #E5E7EB',
    borderRadius: '6px',
    fontSize: '14px',
    outline: 'none',
    backgroundColor: 'white',
    boxSizing: 'border-box',
  },
  priorityGroup: {
    display: 'flex',
    gap: '8px',
  },
  priorityButton: {
    flex: 1,
    padding: '10px',
    border: '1px solid',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: 500,
    cursor: 'pointer',
  },
  modalActions: {
    display: 'flex',
    gap: '12px',
    marginTop: '8px',
  },
  cancelButton: {
    flex: 1,
    padding: '10px',
    backgroundColor: 'white',
    border: '1px solid #E5E7EB',
    borderRadius: '6px',
    fontSize: '14px',
    color: '#374151',
    cursor: 'pointer',
  },
  submitButton: {
    flex: 1,
    padding: '10px',
    backgroundColor: '#22C55E',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    color: 'white',
    cursor: 'pointer',
    fontWeight: 500,
  },
};